server:
  port: 80
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    # 服务消费者启动的时候, 如果这个参数为true, 会拉取eureka-server的服务列表
    fetch-registry: true
    # 每隔5s就重新拉取
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5s告诉eureka-server我还活着
    lease-expiration-duration-in-seconds: 10 # 如果超过10s还没发送心跳, eureka-server就会认为我挂了

# feign 也继承了Hystrix, 只不过默认是关闭的
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000 # feign 的超时设置
        readTimeout: 2000

service-provider:
  ribbon:
    MaxAutoRetriesNextServer: 0 # 在超时的情况下, 在别的同服务的机器上也不重试

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # 设置hystrix的超时时间为3000ms, 之后才调用降级方法