server:
  port: 8888

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: nacos-consumer
          uri: lb://nacos-consumer # 使用服务名而不是ip:port, 可以负载均衡
          predicates:
            - Path=/consumer/** # 匹配/consumer/**的路由可以转发到nacos-consumer服务
          filters:
            - StripPrefix=1 # 去掉consumer前缀 http://127.0.0.1:8888/consumer/h -> http://nacos-consumer/h

        - id: nacos-provider
          uri: lb://nacos-provider
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848